// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/green-tech-2047/AshokaGrid.tsx": () => import("../components/mockups/green-tech-2047/AshokaGrid.tsx"),
  "./components/mockups/green-tech-2047/CommandCenter.tsx": () => import("../components/mockups/green-tech-2047/CommandCenter.tsx"),
  "./components/mockups/green-tech-2047/EditorialIndia.tsx": () => import("../components/mockups/green-tech-2047/EditorialIndia.tsx"),
  "./components/mockups/green-tech-2047/MissionBharat.tsx": () => import("../components/mockups/green-tech-2047/MissionBharat.tsx"),
  "./components/mockups/green-tech-2047/SolarDawn.tsx": () => import("../components/mockups/green-tech-2047/SolarDawn.tsx"),
  "./components/mockups/green-tech-2047/TricolorSweep.tsx": () => import("../components/mockups/green-tech-2047/TricolorSweep.tsx")
};
